# ASP.NET Core hosted Blazor app
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core 3.0 SDK Preview...'
  inputs:
    version: 3.0.100-preview4-011223

- task: Docker@2
  displayName: 'Build Docker image and Push to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub CESARDL'
    repository: mlnetdemos/blazorsentimentanalysis
