# ASP.NET Core hosted Blazor app
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core 3.0 SDK Preview...'
  inputs:
    version: 3.0.100-preview4-011223

- task: Docker@0
  displayName: 'Build Docker image blazorsentimentanalysis'
  inputs:
    azureSubscription: 'PoC Azure Subscription (e3035ac1-c06c-4daf-8939-57b3c5f1f759)'
    azureContainerRegistry: '{"loginServer":"mlnetdemosacr.azurecr.io", "id" : "/subscriptions/e3035ac1-c06c-4daf-8939-57b3c5f1f759/resourceGroups/MLNETDemos/providers/Microsoft.ContainerRegistry/registries/mlnetdemosacr"}'
    dockerFile: BlazorSentimentAnalysis.Server/Dockerfile
    defaultContext: False
    context: '$(System.DefaultWorkingDirectory)'
    imageName: 'mlnetdemosacr/blazorsentimentanalysis:$(Build.BuildId)'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub CESARDL'
    repository: mlnetdemos
    command: push
