# ASP.NET Core hosted Blazor app on Docker container
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: Docker@2
  displayName: 'Build Docker image and push to Docker Hub'
  inputs:
    containerRegistry: 'Docker Hub CESARDL'    
    dockerFile: BlazorSentimentAnalysis.Server/Dockerfile
    buildContext: '$(System.DefaultWorkingDirectory)'
    command: buildAndPush
    repository: mlnetdemos/blazorsentimentanalysisserver
    tags: test